### ISSUE TITLE
do not work imon

### ISSUE THREAD

**Issue by yprivalov** [ErikWegner/imoin#1]
imon 13 don't work

"Response is null."

Firefox 46.0.1
Icinga 1.8.4

**Comment by ErikWegner** [comment]
There was a change in the response between 1.6 and 1.10+. The code actually does not know how to handle 1.8. Please provide an example-response by opening this url: http://yournagios.host/cgi-bin/status.cgi?host=all&style=hostservicedetail&jsonoutput

**Comment by yprivalov** [comment]
http://mynagios.host/**icinga/**cgi-bin/status.cgi?host=all&style=hostservicedetail&jsonoutput

in attach file
[imoin.txt](https://github.com/ErikWegner/imoin/files/263002/imoin.txt)

**Comment by ErikWegner** [comment]
Thank you very much for your help. The next [release](https://github.com/ErikWegner/imoin/releases/tag/V014) should work correctly. Please try again after a signed version is available from Mozilla.

**Comment by ErikWegner** [comment]
Closed. No comment within 14 days.

**Comment by ErikWegner** [comment]
Closed. No comment within 14 days.
