### ISSUE TITLE
Nagios 4.0.7: Connection error. Check settings and log. <jh

### ISSUE THREAD

**Issue by hawkinspeter** [ErikWegner/imoin#11]
I'm getting (Weston) Connection error. Check settings and log. <|h
(I changed the default to be called "Weston")

I've set up the config page to be https://nagios.castelangroup.com/nagios/cgi-bin/statusjson.cgi and when I visit the URL in a browser (with the appropriate username/password), I get a load of data.

The Nagios instance is running 4.0.7.

**Comment by ErikWegner** [comment]
Please change the url in the settings to be `https://nagios.castelangroup.com/nagios`, as described in the [wiki](https://github.com/ErikWegner/imoin/wiki/Configuration#nagios-core-407).

Does it work then?

**Comment by hawkinspeter** [comment]
I'm afraid not - still gives exactly the same error message.

**Comment by ErikWegner** [comment]
Please update to [19.0.0beta1](https://addons.mozilla.org/de/firefox/addon/imoin/versions/beta) and report back.

**Comment by hawkinspeter** [comment]
Still not working: (Default) Connection error. Check settings and log. undefined|undefined

Incidentally, earlier today I installed the extension on a different machine (at work) and had no joy there either.

**Comment by ErikWegner** [comment]
I'm sorry that there is no obvious error. Would you please follow this [wiki article](https://github.com/ErikWegner/imoin/wiki/Debugging#firefox---general-connection-errors) and try to give a hint, why the connection fails?

**Comment by ErikWegner** [comment]
Which backend did you select? The Nagios core backend should not make a request to status.cgi.

Can you open the developer tools for the add on again, trigger a refresh from the imoin panel and have a look at the two requests going to statusjson.cgi?

**Comment by hawkinspeter** [comment]
Nagios Core 4.0.7+

**Comment by hawkinspeter** [comment]
The 2 requests for statusjson.cgi return code 200, but looking at the 2nd one (larger) response, there's a SyntaxError: JSON.parse: bad escaped character at line 3809 column 29 of the JSON data.

Looking at the line, it's not immediately obvious to me why it's complaining:

          "perf_data": "'c:\ Used Space'=14.26Gb;35.56;37.53;0.00;39.51",

**Comment by ErikWegner** [comment]
Where did you see that message? The response preview in the network tab cuts off the data at some point, but before the json parser (for that view) has finished.
Do you see a message in the console tab?

**Comment by hawkinspeter** [comment]
I saw that in the debugger window.

**Comment by ErikWegner** [comment]
Please update to [19.0.0beta2](https://addons.mozilla.org/de/firefox/addon/imoin/versions/beta). What error does the pop-up window show above the summary table?

**Comment by hawkinspeter** [comment]
I get this:
(Default) Could not parse service data.

**Comment by ErikWegner** [comment]
Then there is a problem between the Nagios backend producing the JSON data and Firefox consuming it. Can you narrow down the problem by yourself? Or can you send me the service json data to have a look it?

**Comment by hawkinspeter** [comment]
I'd guess that the issue is to do with line that the debugger identified:
"perf_data": "'c:\ Used Space'=14.26Gb;35.56;37.53;0.00;39.51",

I'll have a look at this tomorrow and send you the JSON.

**Comment by hawkinspeter** [comment]
Hi,

Here's the JSON data from https://nagios.castelangroup.com/nagios/cgi-bin/statusjson.cgi

[json.zip](https://github.com/ErikWegner/imoin/files/1668329/json.zip)

**Comment by hawkinspeter** [comment]
Sorry, that's not the data that you want. The issue is with the response from: 

https://nagios.castelangroup.com/nagios/cgi-bin/statusjson.cgi?query=servicelist&formatoptions=whitespace&details=true

[json.cgi.zip](https://github.com/ErikWegner/imoin/files/1668346/json.cgi.zip)

If I visit that page in the browser, I get the following error that's a bit more specific:

SyntaxError: JSON.parse: bad escaped character at line 3809 column 29 of the JSON data

It looks like it's complaining about the back-slash symbol (\), so I'll see if I can remove that from the config.

**Comment by hawkinspeter** [comment]
Hi,

I've checked my Nagios config and amended one description that used "C:\", but that doesn't make any difference to the PerfData, so it looks like that back-slash is used by the NSClient++ to return performance data.

**Comment by ErikWegner** [comment]
The slash (meaning root directory of drive c:) needs to be encoded by adding a second slash. I do not know if that is a problem of NSClient++ or Nagios. And it is not obvious why the browser console accepts that string while the network preview tab (and the running script) does not.

From how I understand the JSON specification, a backslash followed by a space is not a valid format.
With this information I found this issue: NagiosEnterprises/nagioscore#5 (and [here](http://tracker.nagios.org/view.php?id=623)). The later link says fixed in Nagios Core 4.0.8. Which version do you use?

**Comment by hawkinspeter** [comment]
I'm running 4.0.7 at the moment. I'll have a look at upgrading it next week and see if that resolves the issue (looks hopeful).

**Comment by hawkinspeter** [comment]
I've just got around to upgrading the Nagios server to version 4.3.4 and as if by magic, the IMOIN extension now works.

Thanks for your help.
