### ISSUE TITLE
Add a sound alarm

### ISSUE THREAD

**Issue by macbergil** [ErikWegner/imoin#12]
Hi, 
Is it possible to add a sound alarm when an error or a warning event appears?
It could be a useful feature to enhance the awarness of critical errors
Thanks in advance

PS: I've installed the beta version 19.0.0beta1 for Firefox with Nagios Version 4.1.1, using the option for Nagios HTML parsing. It works well, thanks

**Comment by ErikWegner** [comment]
Please try out [20.0.0alpha1](https://addons.mozilla.org/de/firefox/addon/imoin/versions/beta) and give feedback.

**Comment by ErikWegner** [comment]
Support for sounds added.
