### ISSUE TITLE
Provide Filtering

### ISSUE THREAD

**Issue by majurgens** [ErikWegner/imoin#14]
Would you be able to change this addon to show or count only services/hosts that have certain attributes?
For example, showing things that might be in a transient state (soft) is not always useful. So in this case you might want to filter out all items in a soft state.

Other useful filters would be as shown here:
![image](https://user-images.githubusercontent.com/16494550/36655297-ee93b94a-1b15-11e8-9193-6a70aea1e395.png)

Thanks

**Comment by ErikWegner** [comment]
The first option is now available. Update the add-on to version 21.0.0rc1, open its options and try the available filter for acknowledged problems.

This is not the end of the path, but a big milestone. Now the code supports filtering and further filters can be added more easily.

The remaining options (see screenshot on top of the page) are coming one by one. Each new filter will be a new release.

**Comment by ErikWegner** [comment]
Version 21.0.0rc2 now supports Nagios Core for filtering the acknowledged status.

**Comment by ErikWegner** [comment]
Version 21.1.0 now supports filtering for soft states.

**Comment by ErikWegner** [comment]
The two most requested filter options are available now. To better focus on development, this issue is closed.

Adding more options can be requested by opening a new issue for each option.

**Comment by fleish** [comment]
@ErikWegner I'm testing out these new filter options and am still seeing items (hosts & services) that I have acknowledged in nagios being displayed by the plugin

**Comment by ErikWegner** [comment]
@fleish Which version of nagios are you using? What do you mean by _being displayed by the plugin_? Does the toolbar icon go yellow/red? Does the tab _Errors/Warnings_ contain the service/host in question?

**Comment by fleish** [comment]
@ErikWegner I'm using nagios core 4.3.4. The toolbar is red and the errors/warnings tab contains the services/hosts in question.

**Comment by fleish** [comment]
It exists and is set to true both for a host and a service that show up in the list. Full output attached
[host.txt](https://github.com/ErikWegner/imoin/files/2066893/host.txt)
[service.txt](https://github.com/ErikWegner/imoin/files/2066894/service.txt)

**Comment by ErikWegner** [comment]
Thank you for providing the two data files. I used them in a test, applied the filter and got the expected empty output. Can you confirm that you did activate the _option_ to filter out acknowledged hosts and services and did _update_ the settings?

**Comment by fleish** [comment]
They are both checked and may have found the issue. I have multiple nagios servers configured. The filter seems to be working for the first host listed in the dropdown, but not for the subsequent hosts I have configured.

**Comment by ErikWegner** [comment]
Good point, I'll have a look at that.

**Comment by ErikWegner** [comment]
Having multiple instances does work on my end. Do you have all instances configured as _Nagios Core_ (version dropdown)?

**Comment by fleish** [comment]
Negative, I have some 3.x instances configured as _Nagios HTML parsing_

**Comment by ErikWegner** [comment]
Phew, that is good and bad news: 
![grafik](https://user-images.githubusercontent.com/219169/41329046-a422cf86-6ecb-11e8-91f0-23b7d0adefd9.png)
Please revisit the addon options: The parenthesis contain the list of supported backends. In your case, the _Nagios Core_ instances are supported, but the _HTML parsing_ is not processed.

So the good news is: the code works for supported backends.

The bad: HTML parsing is currently not supported. And the user interface is not clear enough about that fact.

Please open a new issue where you want an implementation of the ack-filter for the HTML parsing backend. And please check your other open issues and name the backends explicitely.
