### ISSUE TITLE
Provide Links to the Relevant Nagios Pages

### ISSUE THREAD

**Issue by majurgens** [ErikWegner/imoin#15]
It would be good if there were links to the relevant Nagios pages. For example, when there are services issue, provide a link to the "services with problems page" (not the all services page). Perhaps also, for each service issue, provide a link directly to that specific page.
Thanks

**Comment by ErikWegner** [comment]
Please test the [beta version](https://imoin.qwirl.eu/#beta)

**Comment by ErikWegner** [comment]
Version 24.0.0 released
