### ISSUE TITLE
Option to filter problems on services whose hosts are down, unreachable, or have been acknowledged

### ISSUE THREAD

**Issue by fleish** [ErikWegner/imoin#19]
Continuing on from the requests in #10 & #14 & #17 & #18 I'd like to request a filter option for problems on services whose hosts are down, unreachable, or have been acknowledged. Thanks!

**Comment by ErikWegner** [comment]
Please try the preview release: https://github.com/ErikWegner/imoin/releases/tag/22.0.0alpha12

**Comment by ErikWegner** [comment]
Version 22.0.0 released
