### ISSUE TITLE
imoin 13 not working under Firefox 45 with Nagios 3.5.1

### ISSUE THREAD

**Issue by beckerma2509** [ErikWegner/imoin#2]
Hello,
I installed imoin and configured our URL for Nagios but imoin Windows leaves blank.
URL is like: http://nagios...de/cgi-bin/nagios3/
When I insert this URL in the Browser and append
status.cgi?host=all&amp;style=hostservicedetail&amp;jsonoutput
I get the Apache authentication window. The User I configured in imoin is automatically filled in with the password from Firefox password manager. After clicking OK I receive the page "Current Network Status". So I believe everything is configured OK, but imoin window is blank.

Regards
- Manfred -

**Comment by ErikWegner** [comment]
Please update to imoin 14 and try again. There was a fix for this issue.

**Comment by ErikWegner** [comment]
Closed after 6 months.
