### ISSUE TITLE
Option to filter problems on services & hosts that are in scheduled downtime

### ISSUE THREAD

**Issue by fleish** [ErikWegner/imoin#20]
Continuing on from the requests in #10 & #14 & #17 & #18 & #19 I'd like to request a filter option for problems on services & hosts that are in scheduled downtime. Thanks!

**Comment by ErikWegner** [comment]
A new [beta version](https://imoin.qwirl.eu/imoin_beta-22.0.1alpha2-fx.xpi) has been published. Please test and feedback.

**Comment by ErikWegner** [comment]
Stable version published
