### ISSUE TITLE
What "URL" for Nagios 2?

### ISSUE THREAD

**Issue by LaurentKEA** [ErikWegner/imoin#3]
I can't make plugin work on Firefox. Can't find any documentation on the "URL" in plugin
What URL can I use?

Here are my parameters:
Version: CGI (Nagios 2)
URL: http://IP_Address/nagios/cgi-bin/status.cgi
Timer Period: 2
Userame/Password: Checked

Regards,
Laurent

**Comment by ErikWegner** [comment]
Please enter the URL without the status.cgi part and leave a comment if it works then.

**Comment by LaurentKEA** [comment]
I've tried with only http://IP_Address/nagios/cgi-bin/
Still not working ?

**Comment by ErikWegner** [comment]
Which version of Nagios/Icinga are you using?

Could you please access 
_http://IP_Address/nagios/cgi-bin/status.cgi?host=all&style=hostservicedetail&jsonoutput_ and have a look at the result? I'd like to get a copy of that json output and have a look at the data structure (You may replace all host names and service descriptions by simple names).

**Comment by LaurentKEA** [comment]
3.0.6
Accessing
http://192.9.200.132/nagios/cgi-bin/status.cgi?host=all&style=hostservicedetail&jsonoutput
works.

2017-07-07 17:59 GMT+02:00 Erik Wegner <notifications@github.com>:

**Comment by ErikWegner** [comment]
Could you please provide an example response?

**Comment by ErikWegner** [comment]
I'm afraid there is no easy fix for the situation. In my memory, when I switched from nagios (2 I presume) to icinga, both were able to output the data in json format. My current research leads me to many resources which tell that nagios from version 4 on can natively output json. Previous versions may install an add-on. Maybe I have had an add-on installed? Maybe I have had a patched version without knowing it?

If you are willing to install an add-on into your nagios 3 installation to output plain json data, tell me which extensions works.

If nagios 4 is also an option, then tell me also.

Please leave comments, which nagios (with or without plugins) versions should be supported.

**Comment by ErikWegner** [comment]
Sorry, no fix at the moment.
