### ISSUE TITLE
hostgroup filter

### ISSUE THREAD

**Issue by FreshDumbledore** [ErikWegner/imoin#37]
I would like to use your extension to monitor a specific hostgroup. I tried populating the URL field with (example) https://server/nagios/cgi-bin/status.cgi?hostgroup=myhostgroup but that yields '(Default) Could not parse host data.'
I guess because the output of a site with a hostgroup filter differs from the default status.cgi output
Could you add support to filter on specific hostgroups?

**Comment by ErikWegner** [comment]
Can you provide a data sample? That would be extremely helpful.
Please have a look at the existing test data files at https://github.com/ErikWegner/imoin/tree/master/test/data..

**Comment by ErikWegner** [comment]
No data provided.
