### ISSUE TITLE
JSON.parse - unexpected character

### ISSUE THREAD

**Issue by Diluke** [ErikWegner/imoin#5]
Error msg: "Connection error. Check settings. SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data"
Nagios server: "Nagios® Core™ 4.3.3"
Add-on configuration: "http:/192.168.146.25/nagios/cgi-bin"

**Comment by ErikWegner** [comment]
Starting implementation of [Nagios Core JSON API](https://labs.nagios.com/2014/06/19/exploring-the-new-json-cgis-in-nagios-core-4-0-7-part-1/)

**Comment by ErikWegner** [comment]
Nagios Core support added, awaiting review for Firefox Add-On

**Comment by ErikWegner** [comment]
Version 17 is available.
