### ISSUE TITLE
SOLVED -> URL path to monitoring Nagios in NagiosCore version and NagiosXI version, update URL in configuration

### ISSUE THREAD

**Issue by naviyork** [ErikWegner/imoin#55]
Hello, I am Ivan, I am a worker in Roche, I am an system administrator and i try to configure the "imoin" extension on "google chrome" on "Nagios XI 5.8.2". Note: Sorry for my English :)
In the "Wiki" on "github" can see that configure the URL  for Nagios in "https://www.example.com/" on check the URL can append "cgi-bin/status.cgi"...
But in my version cant locate the "cgi-bin/status.cgi".  In my case to access to Nagios is "https://xxx.xxx.xxx.xxx/nagiosxi/". The file "status.cgi" is in "nagiosxi"? Or is in other path?
Can change the path of "cgi-bin/status.cgi" or its obligatory change on source code?
The error is...(need to view in raw code)

`
(Corporativo) Connection error: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
"<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /cgi-bin/statusjson.cgi was not found on this server.</p>
</body></html>"

`

Thanks in advance

**Comment by naviyork** [comment]
Hello, I cant find any file with extension "*.cgi", but I find in the file "status.php" in path "/usr/local/nagiosxi/html/includes/components/nagioscore/ui/status.php"... This is the correct file?
Thanyou in advance

**Comment by naviyork** [comment]
Okey... I understand this... Basically the extension is only compatible with the opensource version "Nagios Core", and no with the "Nagios XI" version.
"https://www.nagios.org/downloads/nagios-core/"
Is that posible to make compatible this extension with "XI" version? I can help if you need.
Thank yo in advance.

**Comment by naviyork** [comment]
I found the solution, [https://support.nagios.com/forum/viewtopic.php?t=65977](url) i do a question and response are grateful. In resume the version NagiosXI also has the "Core" version, the URL for NagiosXI version is... https://X.X.X.X/nagiosxi/, and the URL of the Core version is in the https://X.X.X.X/nagios/...
Therefore the URL in the configuration of Imoin is "https://X.X.X.X/nagios/" because the URL of reference in configuration is "https://X.X.X.X/nagios/cgi-bin/status.cgi"

**Comment by naviyork** [comment]
Solved

**Comment by ErikWegner** [comment]
Closing this issue again as author did before.
