### ISSUE TITLE
Error -> Nor work option "No alarm and no highlighting for services whose hosts have been acknowledged"

### ISSUE THREAD

**Issue by naviyork** [ErikWegner/imoin#56]
I have done tests with the "Filters" and they all work except the "No alert and no highlighting for services whose hosts have been acknowledged (Icinga API, Nagios Core)" filter. Basically the application is not filtering the host if it has been acknowledged by a user, in this case another user (not my user).
Can this be fixed? Thanks in advance.

**Comment by ErikWegner** [comment]
I will have a look into it.

**Comment by naviyork** [comment]
Hello, thanks for your dedication, i try and try, and i discovered why occurs, if the host have been acknowledged but the services that depends this host has not been acknowledged, the extension not filter the host (inclusive it acknowledged) and neither the sercives it not acknowledged.
If acknowledged the host and the services depends of host, the filter works.

**Comment by naviyork** [comment]
Sorry for the inconvenience and thanks for the helpful.

**Comment by ErikWegner** [comment]
No further actions required
