### ISSUE TITLE
Nagios

### ISSUE THREAD

**Issue by vt4evr** [ErikWegner/imoin#6]
Hello,
It'd be great if you add possibility to add few nagios servers.

**Comment by ErikWegner** [comment]
Please leave a +1 if this is an interesting feature.

**Comment by schilderdoc** [comment]
Same problem, actually I have 4 different servers to monitor.

**Comment by jesusbagpuss** [comment]
👍 

If it's useful, the code for an old Nagios checker is here:
https://code.google.com/archive/p/nagioschecker/source/default/source
If you download the source, the 'good stuff' is in:
nagioschecker/trunk/srcExtension/chrome/nagioschecker/content/

From a very quick parse, it looks like it gets the status page, and looks for a table with class="status", an parses that to give a summary.

**Comment by ErikWegner** [comment]
This might be useful to add support for older Nagios instances. Thanks for the hint.

**Comment by ErikWegner** [comment]
Support for more instances is currently under development (see branch M18)

**Comment by jesusbagpuss** [comment]
Cool. I'll take a look at that.

I don't have any experience of writing browser extensions, but if there's anything I can do to help (e.g. testing), let me know!

**Comment by ErikWegner** [comment]
Please test the the beta version: https://addons.mozilla.org/de/firefox/addon/imoin/versions/beta

**Comment by jesusbagpuss** [comment]
When I try to edit the extension settings, it doesn't work.
I tried to update existing settings first - the changes I made were not saved.

I then uninstalled / re-installed the extension.
When I click 'update settings' to save the Nagios server details, it drops the data from the input boxes and nothing is saved.

**Comment by jesusbagpuss** [comment]
I think the problem might be in  
https://github.com/ErikWegner/imoin/blob/M18/html/options.js#L130-L139
when comparing it to:
https://github.com/ErikWegner/imoin/blob/master/html/options.js#L4-L16
the values aren't obtained from the UI?

**Comment by ErikWegner** [comment]
@jesusbagpuss Thanks for your feedback. There was a late change in the UI that was not reflected in the code. A new [beta version 18.0.0rc2](https://addons.mozilla.org/de/firefox/addon/imoin/versions/beta) is available.

**Comment by jesusbagpuss** [comment]
Excellent! That fixes the saving-settings problem.

(I've only got an older Nagios server to monitor, but the extension doesn't handle that currently - so can't comment on how well the new version handles multiple Nagios servers)

**Comment by ErikWegner** [comment]
@jesusbagpuss Please have a look at #7 if you would like to see support for Nagios 3.

**Comment by ErikWegner** [comment]
Closed with merge of branch M18 #8
