### ISSUE TITLE
Support for Nagios 3

### ISSUE THREAD

**Issue by ErikWegner** [ErikWegner/imoin#7]
Add support for Nagios 3 by parsing HTML

**Comment by ErikWegner** [comment]
Could you test if the following script does read the list of hosts and services on your Nagios instance? Open a browser console and paste this:

    (function($){
        const basepath = '/nagios'; // no trailing slash

        console.log('Loading hosts');
        
        $.get(basepath + '/cgi-bin/status.cgi?hostgroup=all&style=hostdetail&limit=0')
        .then(function(hostdata) {
            console.log('Loaded');
            const hostdoc = $(hostdata);
            
            $('table.status td[align="left"] a', hostdoc).each(function () {
                const hostname = $(this).text();
                const status = $(this).parents('tr').eq(2).children('td').eq(1).text();
                console.log(hostname, ' => ', status);
            });

            console.log('Loading services');
            
            $.get(basepath + '/cgi-bin/status.cgi?hostgroup=all&style=detail&limit=0')
            .then(function(servicedata) {
                console.log('Loaded');
                const servicedoc = $(servicedata).body;
                let host = null
                $('table.status > tbody > tr', servicedoc).slice(1).each(function() {
                    host = $(this).children('td').eq(0).text().trim() || host;
                    service = $(this).children('td').eq(1).text().trim();
                    if (service == '') {
                        return;
                    }
                    status = $(this).children('td').eq(2).text().trim();
                    console.log(host, '/', service, '=>', status);
                });
            });
        });
    })($)

**Comment by jesusbagpuss** [comment]
Yes it does! 😄

**Comment by jesusbagpuss** [comment]
Yes it does! 😄

**Comment by jesusbagpuss** [comment]
If it's useful, there's also two 'totals' tables that are rendered (see below), which have useful classes to get data for the summary stats:
td.hostTotalsUP
td.hostTotalsDOWN
td.hostTotalsUNREACHABLE
td.hostTotalsPENDING

td.serviceTotalsOK
td.serviceTotalsWARNING
td.serviceTotalsUNKNOWN
td.serviceTotalsCRITICAL
td.serviceTotalsPENDING

If the value for each metric is 0, the class used on the td is just 'hostTotal' or 'serviceTotal'.

```
<table class='hostTotals'>
<tr>
<th class='hostTotals'><a class='hostTotals' href='status.cgi?host=all&hoststatustypes=2'>Up</a></th>
<th class='hostTotals'><a class='hostTotals' href='status.cgi?host=all&hoststatustypes=4'>Down</a></th>
<th class='hostTotals'><a class='hostTotals' href='status.cgi?host=all&hoststatustypes=8'>Unreachable</a></th>
<th class='hostTotals'><a class='hostTotals' href='status.cgi?host=all&hoststatustypes=1'>Pending</a></th>
</tr>
<tr>
<td class='hostTotalsUP'>34</td>
<td class='hostTotals'>0</td>
<td class='hostTotals'>0</td>
<td class='hostTotalsPENDING'>1</td>
</tr>
</table>
```

```
<table class='serviceTotals'>
<tr>
<th class='serviceTotals'><a class='serviceTotals' href='status.cgi?host=all&servicestatustypes=2&hoststatustypes=15'>Ok</a></th>
<th class='serviceTotals'><a class='serviceTotals' href='status.cgi?host=all&servicestatustypes=4&hoststatustypes=15'>Warning</a></th>
<th class='serviceTotals'><a class='serviceTotals' href='status.cgi?host=all&servicestatustypes=8&hoststatustypes=15'>Unknown</a></th>
<th class='serviceTotals'><a class='serviceTotals' href='status.cgi?host=all&servicestatustypes=16&hoststatustypes=15'>Critical</a></th>
<th class='serviceTotals'><a class='serviceTotals' href='status.cgi?host=all&servicestatustypes=1&hoststatustypes=15'>Pending</a></th>
</tr>
<tr>
<td class='serviceTotalsOK'>355</td>
<td class='serviceTotalsWARNING'>2</td>
<td class='serviceTotals'>0</td>
<td class='serviceTotalsCRITICAL'>2</td>
<td class='serviceTotals'>0</td>
</tr>
</table>
```

**Comment by jesusbagpuss** [comment]
Also, there's a summary table for each of the tables above. These would be the lowest cost (processing-wise) to see if there are any issues. If either exist, processing the above tables, or the full status would provide more details.
td.hostTotalsPROBLEMS
td.serviceTotalsPROBLEMS

```
<table class='hostTotals'>
<tr>
<th class='hostTotals'><a class='hostTotals' href='status.cgi?host=all&hoststatustypes=12'><em>All Problems</em></a></th>
<th class='hostTotals'><a class='hostTotals' href='status.cgi?host=all'><em>All Types</em></a></th>
</tr><tr>
<td class='hostTotals'>0</td>
<td class='hostTotals'>35</td>
</tr>
</table>
```


```
<table class='serviceTotals'>
<tr>
<th class='serviceTotals'><a class='serviceTotals' href='status.cgi?host=all&servicestatustypes=28&hoststatustypes=15'><em>All Problems</em></a></th>
<th class='serviceTotals'><a class='serviceTotals' href='status.cgi?host=all&hoststatustypes=15'><em>All Types</em></a></th>
</tr><tr>
<td class='serviceTotalsPROBLEMS'>4</td>
<td class='serviceTotals'>359</td>
</tr>
</table>
```

**Comment by ErikWegner** [comment]
Displaying the status should work with the version [19.0.0alpha1(https://addons.mozilla.org/de/firefox/addon/imoin/versions/beta?page=1#version-19.0.0alpha1). Your feedback is welcome.

**Comment by jesusbagpuss** [comment]
Awesome!
I haven't extensively tested it - but I can now get results from an old Nagios server - excellent work!

The attached screenshot shows an issue with encoded single- and double-quotes around parameters of failed tests.
![imoin](https://user-images.githubusercontent.com/846579/34655019-acce5fba-f3fb-11e7-9afa-4c22d77f63ee.png)

This is the HTML that is parsed for the error shown in the screenshot.:
```
<tr>
<td></td>
<td class="statusBGCRITICAL"><table width="100%" cellspacing="0" cellpadding="0" border="0"><tbody><tr><td align="left"><table cellspacing="0" cellpadding="0" border="0">
<tbody><tr>
<td class="statusBGCRITICAL" valign="center" align="left"><a href="extinfo.cgi?type=2&amp;host=Digital-Library&amp;service=INDEXER">INDEXER</a></td></tr>
</tbody></table>
</td>
<td class="statusBGCRITICAL" align="RIGHT">
<table cellspacing="0" cellpadding="0" border="0">
<tbody><tr>
<td valign="center" align="center"><a href="[URL_REMOVED]" target="_blank"><img src="/nagios/images/notes.gif" alt="View Extra Service Notes" title="View Extra Service Notes" width="20" height="20" border="0"></a></td>
</tr>
</tbody></table>
</td>
</tr></tbody></table></td>
<td class="statusCRITICAL">CRITICAL</td>
<td class="statusBGCRITICAL" nowrap="">2018-01-07 22:33:57</td>
<td class="statusBGCRITICAL" nowrap=""> 0d  2h 24m  6s</td>
<td class="statusBGCRITICAL">3/3</td>
<td class="statusBGCRITICAL" valign="center">HTTP CRITICAL: Status line output matched "200" - string 'indexer: running' not found on '[URL_REMOVED]' - 878 bytes in 0.520 second response time&nbsp;</td>
</tr>
```

Another issue I had was I somehow ended up with the Nagios URL being http://http://servername.
When this line (from nagioshtml.ts) was triggered:
`resolve(Monitor.ErrorMonitorData('Connection error. Check settings and log. ' + a[0] + '|' + a[1]));`
both `a[0]` and `a[1]` were undefined - so I had to dig into the FFox debugger to find the issue (repeated http://).
Would including the URLs being requested be a good suggestion?
I would make debugging 'simple' configuration errors (like getting the URL wrong) much easier.

Would you like me to log both of these as new issues?

Thanks for creating this plugin. The upgrade to the latest Firefox broke our old monitoring plugin - this is an excellent replacement!

**Comment by ErikWegner** [comment]
Please update to [19.0.0beta1](https://addons.mozilla.org/de/firefox/addon/imoin/versions/beta) and report back.

**Comment by jesusbagpuss** [comment]
Looks good to me. Excellent work (again)!

One minor issue when installing the new version - it forgot the Nagios settings that had been entered. Not sure if that normally happens (might just be when you install beta versions?) - doesn't take long to put them back in.

**Comment by ErikWegner** [comment]
I'll have a look at that. Maybe the upgrade code for multiple instances runs again?

**Comment by ErikWegner** [comment]
Support for Nagios 3 added.
