### ISSUE TITLE
Connection error. Check settings. TypeError: this is undefined

### ISSUE THREAD

**Issue by wamlds** [ErikWegner/imoin#9]
First of all, I want to thank you for the programming of this helpful tool.

We have 3 Icinga instances in action. Since version 18.0.1 with CGI (Icinga 1.x) we always get the following error: "Connection error.Check settings.TypeError: this is undefined". The URL set with "/status.cgi?jsonoutput" returns a valid JSON in the browser. Everything worked fine with the previous version, but only one instance was supported. 

Best regards and many thanks

**Comment by ErikWegner** [comment]
Please install version 18.0.2rc2 from [beta channel](https://addons.mozilla.org/de/firefox/addon/imoin/versions/beta). Your feedback is welcome.

**Comment by ErikWegner** [comment]
No feedback provided.
